// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Tz6qRBCQRqmLVYfk7m-8bptKJpkPKqg',
    appId: '1:542888105682:web:bbe1973cd6d76c801dbf0b',
    messagingSenderId: '542888105682',
    projectId: 'laza-a07a2',
    authDomain: 'laza-a07a2.firebaseapp.com',
    storageBucket: 'laza-a07a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJgV4wnNmuHFL5tNmpN5K3H6Lxq1y4Ujo',
    appId: '1:542888105682:android:6c03bb8a5696b35f1dbf0b',
    messagingSenderId: '542888105682',
    projectId: 'laza-a07a2',
    storageBucket: 'laza-a07a2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Tz6qRBCQRqmLVYfk7m-8bptKJpkPKqg',
    appId: '1:542888105682:web:b64cbd582a24a7bb1dbf0b',
    messagingSenderId: '542888105682',
    projectId: 'laza-a07a2',
    authDomain: 'laza-a07a2.firebaseapp.com',
    storageBucket: 'laza-a07a2.firebasestorage.app',
  );

}